export const ADD_BOOK_REQUEST = 'ADD_BOOK_REQUEST';
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const ADD_BOOK_FAILURE = 'ADD_BOOK_FAILURE';

export const GET_BOOK_REQUEST = 'GET_BOOK_REQUEST';
export const GET_BOOK_SUCCESS = 'GET_BOOK_SUCCESS';
export const GET_BOOK_FAILURE = 'GET_BOOK_FAILURE';

export const DELETE_BOOK_REQUEST = 'DELETE_BOOK_REQUEST';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const DELETE_BOOK_FAILURE ='DELETE_BOOK_FAILURE';


export const GET_CHECKOUT_REQUEST = 'GET_CHECKOUT_REQUEST';
export const GET_CHECKOUT_SUCCESS = 'GET_CHECKOUT_SUCCESS';
export const GET_CHECKOUT_FAILURE = 'GET_CHECKOUT_FAILURE';


export const ADD_BOOK_CHECKOUT_REQUEST = 'ADD_BOOK_CHECKOUT_REQUEST';
export const ADD_BOOK_CHECKOUT_SUCCESS = 'ADD_BOOK_CHECKOUT_SUCCESS';
export const ADD_BOOK_CHECKOUT_FAILURE = 'ADD_BOOK_CHECKOUT_FAILURE';
