export const ADD_BOOK_REQUEST = 'ADD_BOOK_REQUEST';
export const ADD_BOOK_SUCCESS = 'ADD_BOOK_SUCCESS';
export const ADD_BOOK_FAILURE = 'ADD_BOOK_FAILURE';

export const GET_BOOK_REQUEST = 'GET_BOOK_REQUEST';
export const GET_BOOK_SUCCESS = 'GET_BOOK_SUCCESS';
export const GET_BOOK_FAILURE = 'GET_BOOK_FAILURE';

export const DELETE_BOOK_REQUEST = 'DELETE_BOOK_REQUEST';
export const DELETE_BOOK_SUCCESS = 'DELETE_BOOK_SUCCESS';
export const DELETE_BOOK_FAILURE ='DELETE_BOOK_FAILURE';


export const GET_CHECKOUT_REQUEST = 'GET_CHECKOUT_REQUEST';
export const GET_CHECKOUT_SUCCESS = 'GET_CHECKOUT_SUCCESS';
export const GET_CHECKOUT_FAILURE = 'GET_CHECKOUT_FAILURE';


export const ADD_BOOK_CHECKOUT_REQUEST = 'ADD_BOOK_CHECKOUT_REQUEST';
export const ADD_BOOK_CHECKOUT_SUCCESS = 'ADD_BOOK_CHECKOUT_SUCCESS';
export const ADD_BOOK_CHECKOUT_FAILURE = 'ADD_BOOK_CHECKOUT_FAILURE';

export const GET_POPULAR_BOOK_REQUEST = 'GET_POPULAR_BOOK_REQUEST';
export const GET_POPULAR_BOOK_SUCCESS = 'GET_POPULAR_BOOK_SUCCESS';
export const GET_POPULAR_BOOK_FAILURE = 'GET_POPULAR_BOOK_FAILURE';

export const GET_BOOK_RECOMMENDATION_REQUEST = 'GET_BOOK_RECOMMENDATION_REQUEST';
export const GET_BOOK_RECOMMENDATION_SUCCESS = 'GET_BOOK_RECOMMENDATION_SUCCESS';
export const GET_BOOK_RECOMMENDATION_FAILURE = 'GET_BOOK_RECOMMENDATION_FAILURE';


export const EDIT_BOOK_REQUEST = "EDIT_BOOK_REQUEST";
export const EDIT_BOOK_SUCCESS = "EDIT_BOOK_SUCCESS";
export const EDIT_BOOK_FAILURE = "EDIT_BOOK_FAILURE";