export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const USER_SIGNOUT = 'USER_SIGNOUT';


export const ADDUSER_REQUEST = 'ADDUSER_REQUEST';
export const ADDUSER_SUCCESS = 'ADDUSER_SUCCESS';
export const ADDUSER_FAILURE = 'ADDUSER_FAILURE';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';
export const UPDATE_FILTERED_USER = 'UPDATE_FILTERED_USER'


export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAILURE = 'DELETE_USER_FAILURE';

export const EDIT_USER_REQUEST = 'EDIT_USER_REQUEST';
export const EDIT_USER_SUCCESS = 'EDIT_USER_SUCCESS';
export const EDIT_USER_FAILURE = 'EDIT_USER_FAILURE';


export const GET_LOG_EVENTS_REQUEST = 'GET_LOG_EVENTS_REQUEST';
export const GET_LOG_EVENTS_SUCCESS = 'GET_LOG_EVENTS_SUCCESS';
export const GET_LOG_EVENTS_FAILURE = 'GET_LOG_EVENTS_FAILURE';

export const GET_USER_CHECKOUT_REQUEST = "GET_USER_CHECKOUT_REQUEST";
export const GET_USER_CHECKOUT_SUCCESS = "GET_USER_CHECKOUT_SUCCESS";
export const GET_USER_CHECKOUT_FAILURE = "GET_USER_CHECKOUT_FAILURE";
export const SAVE_USER_PAYMENT_ACTION = "SAVE_USER_PAYMENT_ACTION";

export const GET_STUDENT_REQUEST = 'GET_STUDENT_REQUEST';
export const GET_STUDENT_SUCCESS = 'GET_STUDENT_SUCCESS';
export const GET_STUDENT_FAILURE = 'GET_STUDENT_FAILURE';




